### ISSUE TITLE
TD network navigation trigger ubergui errors

### ISSUE THREAD

**Issue by AchimKern** [EnviralDesign/UberGui#24]
Hey Lucas,

finally found time to check it out. Great job!

 Small issue here:

Open the toe file and press "u" key to get out of project 1 then press "Enter" key

Traceback (most recent call last):
  File "/project1/container_UG_V4/keyboardin_hotkeys_callbacks", line 23, in onKey
  File "/project1/container_UG_V4/UG4", line 1396, in Trigger_Enter
  File "/project1/container_UG_V4/field/field", line 100, in Set
AttributeError: 'NoneType' object has no attribute 'val'

**Comment by AchimKern** [comment]
seems like a fix is to set 
op("keyboardin_hotkeys").par.panels =".."

**Comment by EnviralDesign** [comment]
awesome thanks for the suggestion! yeah constraining to the UberGui panel is a good idea, that will be in.

however I still have a bug to fix that happens slightly less frequently that has to do with the same underlying part of the code. will have that patched up shortly too.
