### ISSUE TITLE
Errors in touchscreen mode

### ISSUE THREAD

**Issue by AchimKern** [EnviralDesign/UberGui#28]
open UberGui_V4_Release.toe

load simple thing 

touch the RGB "..." 

> nothing happens

touch RGB "..."  again 

```
Traceback (most recent call last):
  File "/project1/container_UG_V4/delayed_double_click", line 4
  File "/project1/container_UG_V4/UG4", line 1321, in Trigger_DelayedDoubleClick
  File "/project1/container_UG_V4/field/field", line 24, in Launch_Delayed
td.Error: File "/project1/container_UG_V4/field/delayed_launch", line 12
  File "/project1/container_UG_V4/field/field", line 47, in Launch
td.AttributeError: 'td.ParCollection' object has no attribute 'Rgbr_cp' Context:/project1/simple_thing
Results of run operation resulted in exception.
```

**Comment by EnviralDesign** [comment]
fixed
